export const SET_POSTS = 'SET_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const FILTER_POST = 'FILTER_POST'
export const DELETE_ALL_POSTS = 'DELETE_ALL_POSTS'
export const ADD_POST = 'ADD_POST'
